version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 5s
      timeout: 3s
      retries: 5

  kafka-1:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment: &kafka-env
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_MIN_IN_SYNC_REPLICAS: 2
      #KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-2:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9093:9092"
    environment:
      <<: *kafka-env
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-3:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9094:9092"
    environment:
      <<: *kafka-env
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    depends_on:
      - kafka-1
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka-1:9092,kafka-2:9092,kafka-3:9092

  init-kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      kafka-1: { condition: service_healthy }
      kafka-2: { condition: service_healthy }
      kafka-3: { condition: service_healthy }
    entrypoint: [ "/bin/sh", "-c" ]
    command: |
      "
      echo 'Waiting for cluster readiness...'
      kafka-topics --bootstrap-server kafka-1:9092 --list

      echo 'Creating notification-topic...'
      kafka-topics --create --if-not-exists --bootstrap-server kafka-1:9092 --topic messages --partitions 3 --replication-factor 3 --config min.insync.replicas=2
      
      # Dead Letter Queue топик
      kafka-topics --create --if-not-exists --bootstrap-server kafka-1:9092 --topic messages-dlq --partitions 1 --replication-factor 3
      
      echo '--- FINAL TOPICS LIST ---'
      kafka-topics --bootstrap-server kafka-1:9092 --list
      "
  
  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8090:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
      - KAFKA_CLUSTERS_0_SCHEMAREGISTRY=http://schema-registry:8081
    depends_on:
      - kafka-1

  consumerservice:
    image: consumerservice
    build: 
      context: .
      dockerfile: ConsumerService/Dockerfile 
    depends_on:
      kafka-1: 
        condition: service_healthy
    environment:
      - KafkaConsumer__BootstrapServers=kafka-1:9092,kafka-2:9092,kafka-3:9092
      - SchemaRegistryUrl=http://schema-registry:8081
  
  producerservice:
    image: producerservice
    build:  
      context: . 
      dockerfile: ProducerService/Dockerfile 
    ports:
      - "8080:8080"
    depends_on:
      kafka-1:
        condition: service_healthy
    environment:
      - KafkaProducer__BootstrapServers=kafka-1:9092,kafka-2:9092,kafka-3:9092
      - SchemaRegistryUrl=http://schema-registry:8081 
